#include "TIdentificatorV2.h"
#include "GSTtree.h"

#include "Headers.hxx"
#include "Constants.hxx"
#include "Math.hxx"
#include "PDG.hxx"

#ifndef TREEOPS_HXX
#define TREEOPS_HXX

void SetElectronBranches_Data(TTree* tree, data_e& de) {
  // electron (46)
  tree->Branch("Q2", &de.Q2);
  tree->Branch("W", &de.W);
  tree->Branch("Nu", &de.Nu);
  tree->Branch("Xb", &de.Xb);
  tree->Branch("Yb", &de.Yb);
  tree->Branch("vxe", &de.vxe);
  tree->Branch("vye", &de.vye);
  tree->Branch("vze", &de.vze);
  tree->Branch("Sector", &de.Sector);
  tree->Branch("TargType", &de.TargType);
  tree->Branch("Px", &de.Px);
  tree->Branch("Py", &de.Py);
  tree->Branch("Pz", &de.Pz);
  tree->Branch("P", &de.P);
  tree->Branch("Betta", &de.Betta);
  tree->Branch("Etot", &de.Etot);
  tree->Branch("Ein", &de.Ein);
  tree->Branch("Eout", &de.Eout);
  tree->Branch("vxec", &de.vxec);
  tree->Branch("vyec", &de.vyec);
  tree->Branch("vzec", &de.vzec);
  tree->Branch("XEC", &de.XEC);
  tree->Branch("YEC", &de.YEC);
  tree->Branch("ZEC", &de.ZEC);
  tree->Branch("PhiLab", &de.PhiLab);
  tree->Branch("ThetaLab", &de.ThetaLab);
  tree->Branch("StatDC", &de.StatDC);
  tree->Branch("DCStatus", &de.DCStatus);
  tree->Branch("StatEC", &de.StatEC);
  tree->Branch("ECStatus", &de.ECStatus);
  tree->Branch("TimeEC", &de.TimeEC);
  tree->Branch("PathEC", &de.PathEC);
  tree->Branch("Chi2EC", &de.Chi2EC);
  tree->Branch("StatSC", &de.StatSC);
  tree->Branch("SCStatus", &de.SCStatus);
  tree->Branch("TimeSC", &de.TimeSC);
  tree->Branch("PathSC", &de.PathSC);
  tree->Branch("StatCC", &de.StatCC);
  tree->Branch("CCStatus", &de.CCStatus);
  tree->Branch("Nphe", &de.Nphe);
  tree->Branch("Chi2CC", &de.Chi2CC);
  tree->Branch("Status", &de.Status);
  tree->Branch("NRowsDC", &de.NRowsDC);
  tree->Branch("NRowsEC", &de.NRowsEC);
  tree->Branch("NRowsSC", &de.NRowsSC);
  tree->Branch("NRowsCC", &de.NRowsCC);
  // evnt (1)
  tree->Branch("evnt", &de.evnt);
}

void SetParticleBranches_Data(TTree* tree, data_p& dp) {
  // electron (46)
  tree->Branch("Q2", &dp.Q2);
  tree->Branch("W", &dp.W);
  tree->Branch("Nu", &dp.Nu);
  tree->Branch("Xb", &dp.Xb);
  tree->Branch("Yb", &dp.Yb);
  tree->Branch("vxe", &dp.vxe);
  tree->Branch("vye", &dp.vye);
  tree->Branch("vze", &dp.vze);
  tree->Branch("SectorEl", &dp.SectorEl);
  tree->Branch("TargType", &dp.TargType);
  tree->Branch("Pex", &dp.Pex);
  tree->Branch("Pey", &dp.Pey);
  tree->Branch("Pez", &dp.Pez);
  tree->Branch("Pe", &dp.Pe);
  tree->Branch("BettaEl", &dp.BettaEl);
  tree->Branch("Etote", &dp.Etote);
  tree->Branch("Eine", &dp.Eine);
  tree->Branch("Eoute", &dp.Eoute);
  tree->Branch("vxec", &dp.vxec);
  tree->Branch("vyec", &dp.vyec);
  tree->Branch("vzec", &dp.vzec);
  tree->Branch("XECe", &dp.XECe);
  tree->Branch("YECe", &dp.YECe);
  tree->Branch("ZECe", &dp.ZECe);
  tree->Branch("PhiLabEl", &dp.PhiLabEl);
  tree->Branch("ThetaLabEl", &dp.ThetaLabEl);
  tree->Branch("StatDCEl", &dp.StatDCEl);
  tree->Branch("DCStatusEl", &dp.DCStatusEl);
  tree->Branch("StatECEl", &dp.StatECEl);
  tree->Branch("ECStatusEl", &dp.ECStatusEl);
  tree->Branch("TimeECEl", &dp.TimeECEl);
  tree->Branch("PathECEl", &dp.PathECEl);
  tree->Branch("Chi2ECEl", &dp.Chi2ECEl);
  tree->Branch("StatSCEl", &dp.StatSCEl);
  tree->Branch("SCStatusEl", &dp.SCStatusEl);
  tree->Branch("TimeSCEl", &dp.TimeSCEl);
  tree->Branch("PathSCEl", &dp.PathSCEl);
  tree->Branch("StatCCEl", &dp.StatCCEl);
  tree->Branch("CCStatusEl", &dp.CCStatusEl);
  tree->Branch("NpheEl", &dp.NpheEl);
  tree->Branch("Chi2CCEl", &dp.Chi2CCEl);
  tree->Branch("StatusEl", &dp.StatusEl);
  tree->Branch("NRowsDCEl", &dp.NRowsDCEl);
  tree->Branch("NRowsECEl", &dp.NRowsECEl);
  tree->Branch("NRowsSCEl", &dp.NRowsSCEl);
  tree->Branch("NRowsCCEl", &dp.NRowsCCEl);
  // particle (49)
  tree->Branch("Eh", &dp.Eh);
  tree->Branch("Zh", &dp.Zh);
  tree->Branch("ThetaPQ", &dp.ThetaPQ);
  tree->Branch("Pt2", &dp.Pt2);
  tree->Branch("Pl2", &dp.Pl2);
  tree->Branch("PhiPQ", &dp.PhiPQ);
  tree->Branch("Mx2", &dp.Mx2);
  tree->Branch("T", &dp.T);
  tree->Branch("PhiLab", &dp.PhiLab);
  tree->Branch("ThetaLab", &dp.ThetaLab);
  tree->Branch("vxh", &dp.vxh);
  tree->Branch("vyh", &dp.vyh);
  tree->Branch("vzh", &dp.vzh);
  tree->Branch("Sector", &dp.Sector);
  tree->Branch("Px", &dp.Px);
  tree->Branch("Py", &dp.Py);
  tree->Branch("Pz", &dp.Pz);
  tree->Branch("P", &dp.P);
  tree->Branch("Betta", &dp.Betta);
  tree->Branch("Mass2", &dp.Mass2);
  tree->Branch("Etot", &dp.Etot);
  tree->Branch("Ein", &dp.Ein);
  tree->Branch("Eout", &dp.Eout);
  tree->Branch("XEC", &dp.XEC);
  tree->Branch("YEC", &dp.YEC);
  tree->Branch("ZEC", &dp.ZEC);
  tree->Branch("pid", &dp.pid);
  tree->Branch("T4", &dp.T4);
  tree->Branch("deltaZ", &dp.deltaZ);
  tree->Branch("StatDC", &dp.StatDC);
  tree->Branch("DCStatus", &dp.DCStatus);
  tree->Branch("StatEC", &dp.StatEC);
  tree->Branch("ECStatus", &dp.ECStatus);
  tree->Branch("TimeEC", &dp.TimeEC);
  tree->Branch("PathEC", &dp.PathEC);
  tree->Branch("Chi2EC", &dp.Chi2EC);
  tree->Branch("StatSC", &dp.StatSC);
  tree->Branch("SCStatus", &dp.SCStatus);
  tree->Branch("TimeSC", &dp.TimeSC);
  tree->Branch("PathSC", &dp.PathSC);
  tree->Branch("StatCC", &dp.StatCC);
  tree->Branch("CCStatus", &dp.CCStatus);
  tree->Branch("Nphe", &dp.Nphe);
  tree->Branch("Chi2CC", &dp.Chi2CC);
  tree->Branch("Status", &dp.Status);
  tree->Branch("NRowsDC", &dp.NRowsDC);
  tree->Branch("NRowsEC", &dp.NRowsEC);
  tree->Branch("NRowsSC", &dp.NRowsSC);
  tree->Branch("NRowsCC", &dp.NRowsCC);
  // event (1)
  tree->Branch("evnt", &dp.evnt);
}

void AssignElectronVar_Data(TIdentificatorV2* t, data_e& de, Int_t evnt, TString dataKind, TString targetOption) {
  // electron (46)
  de.Q2 = t->Q2();
  de.W = t->W();
  de.Nu = t->Nu();
  de.Xb = t->Xb();
  de.Yb = t->Yb();
  de.vxe = t->X(0);
  de.vye = t->Y(0);
  de.vze = t->Z(0);
  de.Sector = t->Sector(0);
  de.Px = t->Px(0);
  de.Py = t->Py(0);
  de.Pz = t->Pz(0);
  de.P = t->Momentum(0);
  de.Betta = t->Betta(0);
  de.Etot = t->Etot(0);
  de.Ein = t->Ein(0);
  de.Eout = t->Eout(0);
  TVector3* fVert = t->GetCorrectedVert();
  de.vxec = fVert->X();
  de.vyec = fVert->Y();
  de.vzec = fVert->Z();
  de.TargType = t->TargTypeSM(dataKind, targetOption, 0);
  de.XEC = t->XEC(0);
  de.YEC = t->YEC(0);
  de.ZEC = t->ZEC(0);
  de.PhiLab = t->PhiLab(0);
  de.ThetaLab = t->ThetaLab(0);
  de.StatDC = t->StatDC(0);
  de.DCStatus = t->DCStatus(0);
  de.StatEC = t->StatEC(0);
  de.ECStatus = t->ECStatus(0);
  de.TimeEC = t->TimeEC(0);
  de.PathEC = t->PathEC(0);
  de.Chi2EC = t->Chi2EC(0);
  de.StatSC = t->StatSC(0);
  de.SCStatus = t->SCStatus(0);
  de.TimeSC = t->TimeSC(0);
  de.PathSC = t->PathSC(0);
  de.StatCC = t->StatCC(0);
  de.CCStatus = t->CCStatus(0);
  de.Nphe = t->Nphe(0);
  de.Chi2CC = t->Chi2CC(0);
  de.Status = t->Status(0);
  de.NRowsDC = t->NRowsDC();
  de.NRowsEC = t->NRowsEC();
  de.NRowsSC = t->NRowsSC();
  de.NRowsCC = t->NRowsCC();
  // evnt (1)
  de.evnt = evnt;
}

void AssignParticleVar_Data(TIdentificatorV2* t, data_p& dp, Int_t row, Int_t evnt, TString dataKind, TString targetOption) {
  // electron (46)
  dp.Q2 = t->Q2();
  dp.W = t->W();
  dp.Nu = t->Nu();
  dp.Xb = t->Xb();
  dp.Yb = t->Yb();
  dp.vxe = t->X(0);
  dp.vye = t->Y(0);
  dp.vze = t->Z(0);
  dp.SectorEl = t->Sector(0);
  dp.Pex = t->Px(0);
  dp.Pey = t->Py(0);
  dp.Pez = t->Pz(0);
  dp.Pe = t->Momentum(0);
  dp.BettaEl = t->Betta(0);
  dp.Etote = t->Etot(0);
  dp.Eine = t->Ein(0);
  dp.Eoute = t->Eout(0);
  TVector3* fVert = t->GetCorrectedVert();
  dp.vxec = fVert->X();
  dp.vyec = fVert->Y();
  dp.vzec = fVert->Z();
  dp.TargType = t->TargTypeSM(dataKind, targetOption, 0);
  dp.XECe = t->XEC(0);
  dp.YECe = t->YEC(0);
  dp.ZECe = t->ZEC(0);
  dp.PhiLabEl = t->PhiLab(0);
  dp.ThetaLabEl = t->ThetaLab(0);
  dp.StatDCEl = t->StatDC(0);
  dp.DCStatusEl = t->DCStatus(0);
  dp.StatECEl = t->StatEC(0);
  dp.ECStatusEl = t->ECStatus(0);
  dp.TimeECEl = t->TimeEC(0);
  dp.PathECEl = t->PathEC(0);
  dp.Chi2ECEl = t->Chi2EC(0);
  dp.StatSCEl = t->StatSC(0);
  dp.SCStatusEl = t->SCStatus(0);
  dp.TimeSCEl = t->TimeSC(0);
  dp.PathSCEl = t->PathSC(0);
  dp.StatCCEl = t->StatCC(0);
  dp.CCStatusEl = t->CCStatus(0);
  dp.NpheEl = t->Nphe(0);
  dp.Chi2CCEl = t->Chi2CC(0);
  dp.StatusEl = t->Status(0);
  dp.NRowsDCEl = t->NRowsDC();
  dp.NRowsECEl = t->NRowsEC();
  dp.NRowsSCEl = t->NRowsSC();
  dp.NRowsCCEl = t->NRowsCC();
  // particle (49)
  dp.pid = particleID(t->GetCategorization(row, dataKind, targetOption));
  dp.vxh = t->X(row);
  dp.vyh = t->Y(row);
  dp.vzh = t->Z(row);
  dp.Sector = t->Sector(row);
  dp.deltaZ = t->Z(row) - fVert->Z();
  dp.XEC = t->XEC(row);
  dp.YEC = t->YEC(row);
  dp.ZEC = t->ZEC(row);
  dp.Etot = t->Etot(row);
  dp.Ein = t->Ein(row);
  dp.Eout = t->Eout(row);
  // let's define some auxiliary Double_t
  Double_t fMass = particleMass(dp.pid);
  TLorentzVector* fGamma = t->GetCorrPhotonMomentum(row);
  Double_t fPx = (dp.pid == 22) * fGamma->Px() + (dp.pid != 22) * t->Px(row);
  Double_t fPy = (dp.pid == 22) * fGamma->Py() + (dp.pid != 22) * t->Py(row);
  Double_t fPz = (dp.pid == 22) * fGamma->Pz() + (dp.pid != 22) * t->Pz(row);
  Double_t fP = TMath::Sqrt(fPx * fPx + fPy * fPy + fPz * fPz);
  Double_t fE = (dp.pid == 22) * fGamma->E() + (dp.pid != 22) * TMath::Sqrt(fMass * fMass + fP * fP);
  Double_t fZ = fE / t->Nu();
  // continue...
  dp.Px = fPx;
  dp.Py = fPy;
  dp.Pz = fPz;
  dp.P = fP;
  dp.PhiLab = PhiLab(fPx, fPy, fPz);
  dp.ThetaLab = ThetaLab(fPx, fPy, fPz);
  dp.Eh = fE;
  dp.Zh = fZ;
  dp.ThetaPQ = ThetaPQ(t->Px(0), t->Py(0), t->Pz(0), fPx, fPy, fPz);
  dp.PhiPQ = PhiPQ(t->Px(0), t->Py(0), t->Pz(0), fPx, fPy, fPz);
  Double_t fCosThetaPQ = (fPz * (kEbeam - t->Pz(0)) - fPx * t->Px(0) - fPy * t->Py(0)) / (TMath::Sqrt(t->Nu() * t->Nu() + t->Q2()) * fP);
  Double_t fPt2 = fP * fP * (1 - fCosThetaPQ * fCosThetaPQ);
  Double_t fPl2 = fP * fP * fCosThetaPQ * fCosThetaPQ;
  dp.Pt2 = fPt2;
  dp.Pl2 = fPl2;
  dp.Mx2 = t->W() * t->W() + fMass * fMass - 2 * fZ * t->Nu() * t->Nu() + 2 * TMath::Sqrt(fPl2 * (t->Nu() * t->Nu() + t->Q2())) - 2 * kMassProton * fZ * t->Nu();
  dp.T = fMass * fMass - 2 * fZ * t->Nu() * t->Nu() + 2 * TMath::Sqrt(fPl2 * (t->Nu() * t->Nu() + t->Q2())) - t->Q2();
  dp.Betta = t->Betta(row);  // BettaMeasured
  dp.Mass2 = fP * fP * (TMath::Power(t->Betta(row), -2) - 1);
  dp.T4 = t->PathSC(0) / 30. - t->TimeSC(0) + t->TimeSC(row) - (t->PathSC(row) / 30.) * TMath::Sqrt(TMath::Power(fMass / fP, 2) + 1);
  // status
  dp.StatDC = t->StatDC(row);
  dp.DCStatus = t->DCStatus(row);
  dp.StatEC = t->StatEC(row);
  dp.ECStatus = t->ECStatus(row);
  dp.TimeEC = t->TimeEC(row);
  dp.PathEC = t->PathEC(row);
  dp.Chi2EC = t->Chi2EC(row);
  dp.StatSC = t->StatSC(row);
  dp.SCStatus = t->SCStatus(row);
  dp.TimeSC = t->TimeSC(row);
  dp.PathSC = t->PathSC(row);
  dp.StatCC = t->StatCC(row);
  dp.CCStatus = t->CCStatus(row);
  dp.Nphe = t->Nphe(row);
  dp.Chi2CC = t->Chi2CC(row);
  dp.Status = t->Status(row);
  dp.NRowsDC = t->NRowsDC();
  dp.NRowsEC = t->NRowsEC();
  dp.NRowsSC = t->NRowsSC();
  dp.NRowsCC = t->NRowsCC();
  // evnt (1)
  dp.evnt = evnt;
}

void SetElectronBranches_Sim(TTree* tree, sim_e& se) {
  // simrec (46)
  tree->Branch("Q2", &se.Q2);
  tree->Branch("W", &se.W);
  tree->Branch("Nu", &se.Nu);
  tree->Branch("Xb", &se.Xb);
  tree->Branch("Yb", &se.Yb);
  tree->Branch("vxe", &se.vxe);
  tree->Branch("vye", &se.vye);
  tree->Branch("vze", &se.vze);
  tree->Branch("Sector", &se.Sector);
  tree->Branch("TargType", &se.TargType);
  tree->Branch("Px", &se.Px);
  tree->Branch("Py", &se.Py);
  tree->Branch("Pz", &se.Pz);
  tree->Branch("P", &se.P);
  tree->Branch("Betta", &se.Betta);
  tree->Branch("Etot", &se.Etot);
  tree->Branch("Ein", &se.Ein);
  tree->Branch("Eout", &se.Eout);
  tree->Branch("vxec", &se.vxec);
  tree->Branch("vyec", &se.vyec);
  tree->Branch("vzec", &se.vzec);
  tree->Branch("XEC", &se.XEC);
  tree->Branch("YEC", &se.YEC);
  tree->Branch("ZEC", &se.ZEC);
  tree->Branch("ThetaLab", &se.ThetaLab);
  tree->Branch("PhiLab", &se.PhiLab);
  tree->Branch("StatDC", &se.StatDC);
  tree->Branch("DCStatus", &se.DCStatus);
  tree->Branch("StatEC", &se.StatEC);
  tree->Branch("ECStatus", &se.ECStatus);
  tree->Branch("TimeEC", &se.TimeEC);
  tree->Branch("PathEC", &se.PathEC);
  tree->Branch("Chi2EC", &se.Chi2EC);
  tree->Branch("StatSC", &se.StatSC);
  tree->Branch("SCStatus", &se.SCStatus);
  tree->Branch("TimeSC", &se.TimeSC);
  tree->Branch("PathSC", &se.PathSC);
  tree->Branch("StatCC", &se.StatCC);
  tree->Branch("CCStatus", &se.CCStatus);
  tree->Branch("Nphe", &se.Nphe);
  tree->Branch("Chi2CC", &se.Chi2CC);
  tree->Branch("Status", &se.Status);
  tree->Branch("NRowsDC", &se.NRowsDC);
  tree->Branch("NRowsEC", &se.NRowsEC);
  tree->Branch("NRowsSC", &se.NRowsSC);
  tree->Branch("NRowsCC", &se.NRowsCC);
  // event (1)
  tree->Branch("evnt", &se.evnt);
  // gsim (17)
  tree->Branch("mc_Q2", &se.mc_Q2);
  tree->Branch("mc_W", &se.mc_W);
  tree->Branch("mc_Nu", &se.mc_Nu);
  tree->Branch("mc_Xb", &se.mc_Xb);
  tree->Branch("mc_Yb", &se.mc_Yb);
  tree->Branch("mc_vxe", &se.mc_vxe);
  tree->Branch("mc_vye", &se.mc_vye);
  tree->Branch("mc_vze", &se.mc_vze);
  tree->Branch("mc_Sector", &se.mc_Sector);
  tree->Branch("mc_TargType", &se.mc_TargType);
  tree->Branch("mc_Px", &se.mc_Px);
  tree->Branch("mc_Py", &se.mc_Py);
  tree->Branch("mc_Pz", &se.mc_Pz);
  tree->Branch("mc_P", &se.mc_P);
  tree->Branch("mc_Betta", &se.mc_Betta);
  tree->Branch("mc_ThetaLab", &se.mc_ThetaLab);
  tree->Branch("mc_PhiLab", &se.mc_PhiLab);
}

void SetParticleBranches_Sim(TTree* tree, sim_p& sp) {
  // simrec electron (46)
  tree->Branch("Q2", &sp.Q2);
  tree->Branch("W", &sp.W);
  tree->Branch("Nu", &sp.Nu);
  tree->Branch("Xb", &sp.Xb);
  tree->Branch("Yb", &sp.Yb);
  tree->Branch("vxe", &sp.vxe);
  tree->Branch("vye", &sp.vye);
  tree->Branch("vze", &sp.vze);
  tree->Branch("SectorEl", &sp.SectorEl);
  tree->Branch("TargType", &sp.TargType);
  tree->Branch("Pex", &sp.Pex);
  tree->Branch("Pey", &sp.Pey);
  tree->Branch("Pez", &sp.Pez);
  tree->Branch("Pe", &sp.Pe);
  tree->Branch("BettaEl", &sp.BettaEl);
  tree->Branch("Etote", &sp.Etote);
  tree->Branch("Eine", &sp.Eine);
  tree->Branch("Eoute", &sp.Eoute);
  tree->Branch("vxec", &sp.vxec);
  tree->Branch("vyec", &sp.vyec);
  tree->Branch("vzec", &sp.vzec);
  tree->Branch("XECe", &sp.XECe);
  tree->Branch("YECe", &sp.YECe);
  tree->Branch("ZECe", &sp.ZECe);
  tree->Branch("ThetaLabEl", &sp.ThetaLabEl);
  tree->Branch("PhiLabEl", &sp.PhiLabEl);
  tree->Branch("StatDCEl", &sp.StatDCEl);
  tree->Branch("DCStatusEl", &sp.DCStatusEl);
  tree->Branch("StatECEl", &sp.StatECEl);
  tree->Branch("ECStatusEl", &sp.ECStatusEl);
  tree->Branch("TimeECEl", &sp.TimeECEl);
  tree->Branch("PathECEl", &sp.PathECEl);
  tree->Branch("Chi2ECEl", &sp.Chi2ECEl);
  tree->Branch("StatSCEl", &sp.StatSCEl);
  tree->Branch("SCStatusEl", &sp.SCStatusEl);
  tree->Branch("TimeSCEl", &sp.TimeSCEl);
  tree->Branch("PathSCEl", &sp.PathSCEl);
  tree->Branch("StatCCEl", &sp.StatCCEl);
  tree->Branch("CCStatusEl", &sp.CCStatusEl);
  tree->Branch("NpheEl", &sp.NpheEl);
  tree->Branch("Chi2CCEl", &sp.Chi2CCEl);
  tree->Branch("StatusEl", &sp.StatusEl);
  tree->Branch("NRowsDCEl", &sp.NRowsDCEl);
  tree->Branch("NRowsECEl", &sp.NRowsECEl);
  tree->Branch("NRowsSCEl", &sp.NRowsSCEl);
  tree->Branch("NRowsCCEl", &sp.NRowsCCEl);
  // simrec particle (49)
  tree->Branch("Eh", &sp.Eh);
  tree->Branch("Zh", &sp.Zh);
  tree->Branch("ThetaPQ", &sp.ThetaPQ);
  tree->Branch("Pt2", &sp.Pt2);
  tree->Branch("Pl2", &sp.Pl2);
  tree->Branch("PhiPQ", &sp.PhiPQ);
  tree->Branch("Mx2", &sp.Mx2);
  tree->Branch("T", &sp.T);
  tree->Branch("ThetaLab", &sp.ThetaLab);
  tree->Branch("PhiLab", &sp.PhiLab);
  tree->Branch("vxh", &sp.vxh);
  tree->Branch("vyh", &sp.vyh);
  tree->Branch("vzh", &sp.vzh);
  tree->Branch("Sector", &sp.Sector);
  tree->Branch("Px", &sp.Px);
  tree->Branch("Py", &sp.Py);
  tree->Branch("Pz", &sp.Pz);
  tree->Branch("P", &sp.P);
  tree->Branch("Betta", &sp.Betta);
  tree->Branch("Mass2", &sp.Mass2);
  tree->Branch("Etot", &sp.Etot);
  tree->Branch("Ein", &sp.Ein);
  tree->Branch("Eout", &sp.Eout);
  tree->Branch("XEC", &sp.XEC);
  tree->Branch("YEC", &sp.YEC);
  tree->Branch("ZEC", &sp.ZEC);
  tree->Branch("pid", &sp.pid);
  tree->Branch("T4", &sp.T4);
  tree->Branch("deltaZ", &sp.deltaZ);
  tree->Branch("StatDC", &sp.StatDC);
  tree->Branch("DCStatus", &sp.DCStatus);
  tree->Branch("StatEC", &sp.StatEC);
  tree->Branch("ECStatus", &sp.ECStatus);
  tree->Branch("TimeEC", &sp.TimeEC);
  tree->Branch("PathEC", &sp.PathEC);
  tree->Branch("Chi2EC", &sp.Chi2EC);
  tree->Branch("StatSC", &sp.StatSC);
  tree->Branch("SCStatus", &sp.SCStatus);
  tree->Branch("TimeSC", &sp.TimeSC);
  tree->Branch("PathSC", &sp.PathSC);
  tree->Branch("StatCC", &sp.StatCC);
  tree->Branch("CCStatus", &sp.CCStatus);
  tree->Branch("Nphe", &sp.Nphe);
  tree->Branch("Chi2CC", &sp.Chi2CC);
  tree->Branch("Status", &sp.Status);
  tree->Branch("NRowsDC", &sp.NRowsDC);
  tree->Branch("NRowsEC", &sp.NRowsEC);
  tree->Branch("NRowsSC", &sp.NRowsSC);
  tree->Branch("NRowsCC", &sp.NRowsCC);
  // event-related (1)
  tree->Branch("evnt", &sp.evnt);
  // gsim electron (17)
  tree->Branch("mc_Q2", &sp.mc_Q2);
  tree->Branch("mc_W", &sp.mc_W);
  tree->Branch("mc_Nu", &sp.mc_Nu);
  tree->Branch("mc_Xb", &sp.mc_Xb);
  tree->Branch("mc_Yb", &sp.mc_Yb);
  tree->Branch("mc_vxe", &sp.mc_vxe);
  tree->Branch("mc_vye", &sp.mc_vye);
  tree->Branch("mc_vze", &sp.mc_vze);
  tree->Branch("mc_SectorEl", &sp.mc_SectorEl);
  tree->Branch("mc_TargType", &sp.mc_TargType);
  tree->Branch("mc_Pex", &sp.mc_Pex);
  tree->Branch("mc_Pey", &sp.mc_Pey);
  tree->Branch("mc_Pez", &sp.mc_Pez);
  tree->Branch("mc_Pe", &sp.mc_Pe);
  tree->Branch("mc_BettaEl", &sp.mc_BettaEl);
  tree->Branch("mc_ThetaLabEl", &sp.mc_ThetaLabEl);
  tree->Branch("mc_PhiLabEl", &sp.mc_PhiLabEl);
  // gsim particle (22)
  tree->Branch("mc_Eh", &sp.mc_Eh);
  tree->Branch("mc_Zh", &sp.mc_Zh);
  tree->Branch("mc_ThetaPQ", &sp.mc_ThetaPQ);
  tree->Branch("mc_Pt2", &sp.mc_Pt2);
  tree->Branch("mc_Pl2", &sp.mc_Pl2);
  tree->Branch("mc_PhiPQ", &sp.mc_PhiPQ);
  tree->Branch("mc_Mx2", &sp.mc_Mx2);
  tree->Branch("mc_T", &sp.mc_T);
  tree->Branch("mc_ThetaLab", &sp.mc_ThetaLab);
  tree->Branch("mc_PhiLab", &sp.mc_PhiLab);
  tree->Branch("mc_vxh", &sp.mc_vxh);
  tree->Branch("mc_vyh", &sp.mc_vyh);
  tree->Branch("mc_vzh", &sp.mc_vzh);
  tree->Branch("mc_Sector", &sp.mc_Sector);
  tree->Branch("mc_Px", &sp.mc_Px);
  tree->Branch("mc_Py", &sp.mc_Py);
  tree->Branch("mc_Pz", &sp.mc_Pz);
  tree->Branch("mc_P", &sp.mc_P);
  tree->Branch("mc_Betta", &sp.mc_Betta);
  tree->Branch("mc_Mass2", &sp.mc_Mass2);
  tree->Branch("mc_pid", &sp.mc_pid);
  tree->Branch("mc_deltaZ", &sp.mc_deltaZ);
}

void NullElectronVar_SIMREC(sim_e& se) {
  // (46 variables)
  se.Q2 = INVLD;
  se.W = INVLD;
  se.Nu = INVLD;
  se.Xb = INVLD;
  se.Yb = INVLD;
  se.vxe = INVLD;
  se.vye = INVLD;
  se.vze = INVLD;
  se.Sector = INVLD;
  se.Px = INVLD;
  se.Py = INVLD;
  se.Pz = INVLD;
  se.P = INVLD;
  se.Betta = INVLD;
  se.Etot = INVLD;
  se.Ein = INVLD;
  se.Eout = INVLD;
  se.vxec = INVLD;
  se.vyec = INVLD;
  se.vzec = INVLD;
  se.TargType = INVLD;
  se.XEC = INVLD;
  se.YEC = INVLD;
  se.ZEC = INVLD;
  se.ThetaLab = INVLD;
  se.PhiLab = INVLD;
  se.StatDC = INVLD;
  se.DCStatus = INVLD;
  se.StatEC = INVLD;
  se.ECStatus = INVLD;
  se.TimeEC = INVLD;
  se.PathEC = INVLD;
  se.Chi2EC = INVLD;
  se.StatSC = INVLD;
  se.SCStatus = INVLD;
  se.TimeSC = INVLD;
  se.PathSC = INVLD;
  se.StatCC = INVLD;
  se.CCStatus = INVLD;
  se.Nphe = INVLD;
  se.Chi2CC = INVLD;
  se.Status = INVLD;
  se.NRowsDC = INVLD;
  se.NRowsEC = INVLD;
  se.NRowsSC = INVLD;
  se.NRowsCC = INVLD;
}

void NullParticleVar_SIMREC(sim_p& sp) {
  // electron (46)
  sp.Q2 = INVLD;
  sp.W = INVLD;
  sp.Nu = INVLD;
  sp.Xb = INVLD;
  sp.Yb = INVLD;
  sp.vxe = INVLD;
  sp.vye = INVLD;
  sp.vze = INVLD;
  sp.SectorEl = INVLD;
  sp.Pex = INVLD;
  sp.Pey = INVLD;
  sp.Pez = INVLD;
  sp.Pe = INVLD;
  sp.BettaEl = INVLD;
  sp.Etote = INVLD;
  sp.Eine = INVLD;
  sp.Eoute = INVLD;
  sp.vxec = INVLD;
  sp.vyec = INVLD;
  sp.vzec = INVLD;
  sp.TargType = INVLD;
  sp.XECe = INVLD;
  sp.YECe = INVLD;
  sp.ZECe = INVLD;
  sp.ThetaLabEl = INVLD;
  sp.PhiLabEl = INVLD;
  sp.StatDCEl = INVLD;
  sp.DCStatusEl = INVLD;
  sp.StatECEl = INVLD;
  sp.ECStatusEl = INVLD;
  sp.TimeECEl = INVLD;
  sp.PathECEl = INVLD;
  sp.Chi2ECEl = INVLD;
  sp.StatSCEl = INVLD;
  sp.SCStatusEl = INVLD;
  sp.TimeSCEl = INVLD;
  sp.PathSCEl = INVLD;
  sp.StatCCEl = INVLD;
  sp.CCStatusEl = INVLD;
  sp.NpheEl = INVLD;
  sp.Chi2CCEl = INVLD;
  sp.StatusEl = INVLD;
  sp.NRowsDCEl = INVLD;
  sp.NRowsECEl = INVLD;
  sp.NRowsSCEl = INVLD;
  sp.NRowsCCEl = INVLD;
  // particle (49)
  sp.pid = INVLD;
  sp.Eh = INVLD;
  sp.Zh = INVLD;
  sp.ThetaPQ = INVLD;
  sp.PhiPQ = INVLD;
  sp.Pt2 = INVLD;
  sp.Pl2 = INVLD;
  sp.Mx2 = INVLD;
  sp.T = INVLD;
  sp.ThetaLab = INVLD;
  sp.PhiLab = INVLD;
  sp.T4 = INVLD;
  sp.vxh = INVLD;
  sp.vyh = INVLD;
  sp.vzh = INVLD;
  sp.Sector = INVLD;
  sp.Px = INVLD;
  sp.Py = INVLD;
  sp.Pz = INVLD;
  sp.P = INVLD;
  sp.Betta = INVLD;
  sp.Mass2 = INVLD;
  sp.Etot = INVLD;
  sp.Ein = INVLD;
  sp.Eout = INVLD;
  sp.XEC = INVLD;
  sp.YEC = INVLD;
  sp.ZEC = INVLD;
  sp.deltaZ = INVLD;
  sp.StatDC = INVLD;
  sp.DCStatus = INVLD;
  sp.StatEC = INVLD;
  sp.ECStatus = INVLD;
  sp.TimeEC = INVLD;
  sp.PathEC = INVLD;
  sp.Chi2EC = INVLD;
  sp.StatSC = INVLD;
  sp.SCStatus = INVLD;
  sp.TimeSC = INVLD;
  sp.PathSC = INVLD;
  sp.StatCC = INVLD;
  sp.CCStatus = INVLD;
  sp.Nphe = INVLD;
  sp.Chi2CC = INVLD;
  sp.Status = INVLD;
  sp.NRowsDC = INVLD;
  sp.NRowsEC = INVLD;
  sp.NRowsSC = INVLD;
  sp.NRowsCC = INVLD;
}

void NullElectronVar_GSIM(sim_e& se) {
  // (17 variables)
  se.mc_Q2 = INVLD;
  se.mc_W = INVLD;
  se.mc_Nu = INVLD;
  se.mc_Xb = INVLD;
  se.mc_Yb = INVLD;
  se.mc_vxe = INVLD;
  se.mc_vye = INVLD;
  se.mc_vze = INVLD;
  se.mc_Sector = INVLD;
  se.mc_TargType = INVLD;
  se.mc_Px = INVLD;
  se.mc_Py = INVLD;
  se.mc_Pz = INVLD;
  se.mc_P = INVLD;
  se.mc_Betta = INVLD;
  se.mc_ThetaLab = INVLD;
  se.mc_PhiLab = INVLD;
}

void NullParticleVar_GSIM(sim_p& sp) {
  // gsim electron (17)
  sp.mc_Q2 = INVLD;
  sp.mc_W = INVLD;
  sp.mc_Nu = INVLD;
  sp.mc_Xb = INVLD;
  sp.mc_Yb = INVLD;
  sp.mc_vxe = INVLD;
  sp.mc_vye = INVLD;
  sp.mc_vze = INVLD;
  sp.mc_SectorEl = INVLD;
  sp.mc_TargType = INVLD;
  sp.mc_Pex = INVLD;
  sp.mc_Pey = INVLD;
  sp.mc_Pez = INVLD;
  sp.mc_Pe = INVLD;
  sp.mc_BettaEl = INVLD;
  sp.mc_ThetaLabEl = INVLD;
  sp.mc_PhiLabEl = INVLD;
  // gsim particle (22)
  sp.mc_Eh = INVLD;
  sp.mc_Zh = INVLD;
  sp.mc_ThetaPQ = INVLD;
  sp.mc_Pt2 = INVLD;
  sp.mc_Pl2 = INVLD;
  sp.mc_PhiPQ = INVLD;
  sp.mc_ThetaLab = INVLD;
  sp.mc_PhiLab = INVLD;
  sp.mc_Mx2 = INVLD;
  sp.mc_T = INVLD;
  sp.mc_vxh = INVLD;
  sp.mc_vyh = INVLD;
  sp.mc_vzh = INVLD;
  sp.mc_Sector = INVLD;
  sp.mc_Px = INVLD;
  sp.mc_Py = INVLD;
  sp.mc_Pz = INVLD;
  sp.mc_P = INVLD;
  sp.mc_Betta = INVLD;
  sp.mc_Mass2 = INVLD;
  sp.mc_deltaZ = INVLD;
  sp.mc_pid = INVLD;
}

void AssignElectronVar_SIMREC(TIdentificatorV2* t, sim_e& se, Int_t evnt, TString dataKind, TString targetOption) {
  // simrec (46)
  se.Q2 = t->Q2();
  se.W = t->W();
  se.Nu = t->Nu();
  se.Xb = t->Xb();
  se.Yb = t->Yb();
  se.vxe = t->X(0);
  se.vye = t->Y(0);
  se.vze = t->Z(0);
  se.Sector = t->Sector(0);
  se.Px = t->Px(0);
  se.Py = t->Py(0);
  se.Pz = t->Pz(0);
  se.P = t->Momentum(0);
  se.Betta = t->Betta(0);
  se.Etot = t->Etot(0);
  se.Ein = t->Ein(0);
  se.Eout = t->Eout(0);
  TVector3* fVert = t->GetCorrectedVert();
  se.vxec = fVert->X();
  se.vyec = fVert->Y();
  se.vzec = fVert->Z();
  se.TargType = t->TargTypeSM(dataKind, targetOption, 0);
  se.XEC = t->XEC(0);
  se.YEC = t->YEC(0);
  se.ZEC = t->ZEC(0);
  se.ThetaLab = t->ThetaLab(0);
  se.PhiLab = t->PhiLab(0);
  se.StatDC = t->StatDC(0);
  se.DCStatus = t->DCStatus(0);
  se.StatEC = t->StatEC(0);
  se.ECStatus = t->ECStatus(0);
  se.TimeEC = t->TimeEC(0);
  se.PathEC = t->PathEC(0);
  se.Chi2EC = t->Chi2EC(0);
  se.StatSC = t->StatSC(0);
  se.SCStatus = t->SCStatus(0);
  se.TimeSC = t->TimeSC(0);
  se.PathSC = t->PathSC(0);
  se.StatCC = t->StatCC(0);
  se.CCStatus = t->CCStatus(0);
  se.Nphe = t->Nphe(0);
  se.Chi2CC = t->Chi2CC(0);
  se.Status = t->Status(0);
  se.NRowsDC = t->NRowsDC();
  se.NRowsEC = t->NRowsEC();
  se.NRowsSC = t->NRowsSC();
  se.NRowsCC = t->NRowsCC();
}

void AssignElectronVar_GSIM(TIdentificatorV2* t, sim_e& se, Int_t evnt, TString dataKind, TString targetOption) {
  // event-related (1)
  se.evnt = evnt;
  // gsim (17)
  se.mc_Q2 = t->Q2(1);
  se.mc_W = t->W(1);
  se.mc_Nu = t->Nu(1);
  se.mc_Xb = t->Xb(1);
  se.mc_Yb = t->Yb(1);
  se.mc_vxe = t->X(0, 1);
  se.mc_vye = t->Y(0, 1);
  se.mc_vze = t->Z(0, 1);
  se.mc_Sector = t->Sector(0, 1);
  se.mc_Px = t->Px(0, 1);
  se.mc_Py = t->Py(0, 1);
  se.mc_Pz = t->Pz(0, 1);
  se.mc_P = t->Momentum(0, 1);
  se.mc_Betta = t->Betta(0, 1);
  se.mc_ThetaLab = t->ThetaLab(0, 1);
  se.mc_PhiLab = t->PhiLab(0, 1);
  se.mc_TargType = t->TargTypeSM(dataKind, targetOption, 1);
}

void AssignParticleVar_SIMREC(TIdentificatorV2* t, sim_p& sp, Int_t row, Int_t evnt, TString dataKind, TString targetOption) {
  // simrec electron (46)
  sp.Q2 = t->Q2();
  sp.W = t->W();
  sp.Nu = t->Nu();
  sp.Xb = t->Xb();
  sp.Yb = t->Yb();
  sp.vxe = t->X(0);
  sp.vye = t->Y(0);
  sp.vze = t->Z(0);
  sp.SectorEl = t->Sector(0);
  sp.Pex = t->Px(0);
  sp.Pey = t->Py(0);
  sp.Pez = t->Pz(0);
  sp.Pe = t->Momentum(0);
  sp.BettaEl = t->Betta(0);
  sp.Etote = t->Etot(0);
  sp.Eine = t->Ein(0);
  sp.Eoute = t->Eout(0);
  TVector3* fVert = t->GetCorrectedVert();
  sp.vxec = fVert->X();
  sp.vyec = fVert->Y();
  sp.vzec = fVert->Z();
  sp.TargType = t->TargTypeSM(dataKind, targetOption, 0);
  sp.XECe = t->XEC(0);
  sp.YECe = t->YEC(0);
  sp.ZECe = t->ZEC(0);
  sp.PhiLabEl = t->PhiLab(0);
  sp.ThetaLabEl = t->ThetaLab(0);
  sp.StatDCEl = t->StatDC(0);
  sp.DCStatusEl = t->DCStatus(0);
  sp.StatECEl = t->StatEC(0);
  sp.ECStatusEl = t->ECStatus(0);
  sp.TimeECEl = t->TimeEC(0);
  sp.PathECEl = t->PathEC(0);
  sp.Chi2ECEl = t->Chi2EC(0);
  sp.StatSCEl = t->StatSC(0);
  sp.SCStatusEl = t->SCStatus(0);
  sp.TimeSCEl = t->TimeSC(0);
  sp.PathSCEl = t->PathSC(0);
  sp.StatCCEl = t->StatCC(0);
  sp.CCStatusEl = t->CCStatus(0);
  sp.NpheEl = t->Nphe(0);
  sp.Chi2CCEl = t->Chi2CC(0);
  sp.StatusEl = t->Status(0);
  sp.NRowsDCEl = t->NRowsDC();
  sp.NRowsECEl = t->NRowsEC();
  sp.NRowsSCEl = t->NRowsSC();
  sp.NRowsCCEl = t->NRowsCC();
  // simrec particle (49)
  sp.pid = particleID(t->GetCategorization(row, dataKind, targetOption));  // in PDG numbering scheme
  sp.vxh = t->X(row);
  sp.vyh = t->Y(row);
  sp.vzh = t->Z(row);
  sp.Sector = t->Sector(row);
  sp.deltaZ = t->Z(row) - fVert->Z();
  sp.XEC = t->XEC(row);
  sp.YEC = t->YEC(row);
  sp.ZEC = t->ZEC(row);
  sp.Etot = t->Etot(row);
  sp.Ein = t->Ein(row);
  sp.Eout = t->Eout(row);
  // let's define some auxiliary Double_t
  Double_t fMass = particleMass(sp.pid);
  TLorentzVector* fGamma = t->GetCorrPhotonMomentum(row);
  Double_t fPx = (sp.pid == 22) * fGamma->Px() + (sp.pid != 22) * t->Px(row);
  Double_t fPy = (sp.pid == 22) * fGamma->Py() + (sp.pid != 22) * t->Py(row);
  Double_t fPz = (sp.pid == 22) * fGamma->Pz() + (sp.pid != 22) * t->Pz(row);
  Double_t fP = TMath::Sqrt(fPx * fPx + fPy * fPy + fPz * fPz);
  Double_t fE = (sp.pid == 22) * fGamma->E() + (sp.pid != 22) * TMath::Sqrt(fMass * fMass + fP * fP);
  Double_t fZ = fE / t->Nu();
  // continue...
  sp.Px = fPx;
  sp.Py = fPy;
  sp.Pz = fPz;
  sp.P = fP;
  sp.PhiLab = PhiLab(fPx, fPy, fPz);
  sp.ThetaLab = ThetaLab(fPx, fPy, fPz);
  sp.Eh = fE;
  sp.Zh = fZ;
  sp.ThetaPQ = ThetaPQ(t->Px(0), t->Py(0), t->Pz(0), fPx, fPy, fPz);
  sp.PhiPQ = PhiPQ(t->Px(0), t->Py(0), t->Pz(0), fPx, fPy, fPz);
  Double_t fCosThetaPQ = (fPz * (kEbeam - t->Pz(0)) - fPx * t->Px(0) - fPy * t->Py(0)) / (TMath::Sqrt(t->Nu() * t->Nu() + t->Q2()) * fP);
  Double_t fPt2 = fP * fP * (1 - fCosThetaPQ * fCosThetaPQ);
  Double_t fPl2 = fP * fP * fCosThetaPQ * fCosThetaPQ;
  sp.Pt2 = fPt2;
  sp.Pl2 = fPl2;
  sp.Mx2 = t->W() * t->W() + fMass * fMass - 2 * fZ * t->Nu() * t->Nu() + 2 * TMath::Sqrt(fPl2 * (t->Nu() * t->Nu() + t->Q2())) - 2 * kMassProton * fZ * t->Nu();
  sp.T = fMass * fMass - 2 * fZ * t->Nu() * t->Nu() + 2 * TMath::Sqrt(fPl2 * (t->Nu() * t->Nu() + t->Q2())) - t->Q2();
  sp.Betta = t->Betta(row);  // BettaMeasured
  sp.Mass2 = fP * fP * (TMath::Power(t->Betta(row), -2) - 1);
  sp.T4 = t->PathSC(0) / 30. - t->TimeSC(0) + t->TimeSC(row) - (t->PathSC(row) / 30.) * TMath::Sqrt(TMath::Power(fMass / fP, 2) + 1);
  // status
  sp.StatDC = t->StatDC(row);
  sp.DCStatus = t->DCStatus(row);
  sp.StatEC = t->StatEC(row);
  sp.ECStatus = t->ECStatus(row);
  sp.TimeEC = t->TimeEC(row);
  sp.PathEC = t->PathEC(row);
  sp.Chi2EC = t->Chi2EC(row);
  sp.StatSC = t->StatSC(row);
  sp.SCStatus = t->SCStatus(row);
  sp.TimeSC = t->TimeSC(row);
  sp.PathSC = t->PathSC(row);
  sp.StatCC = t->StatCC(row);
  sp.CCStatus = t->CCStatus(row);
  sp.Nphe = t->Nphe(row);
  sp.Chi2CC = t->Chi2CC(row);
  sp.Status = t->Status(row);
  sp.NRowsDC = t->NRowsDC();
  sp.NRowsEC = t->NRowsEC();
  sp.NRowsSC = t->NRowsSC();
  sp.NRowsCC = t->NRowsCC();
}

void AssignParticleVar_GSIM(TIdentificatorV2* t, sim_p& sp, Int_t row, Int_t evnt, TString dataKind, TString targetOption) {
  // event-related (1)
  sp.evnt = evnt;
  // gsim electron (17)
  sp.mc_Q2 = t->Q2(1);
  sp.mc_W = t->W(1);
  sp.mc_Nu = t->Nu(1);
  sp.mc_Xb = t->Xb(1);
  sp.mc_Yb = t->Yb(1);
  sp.mc_vxe = t->X(0, 1);
  sp.mc_vye = t->Y(0, 1);
  sp.mc_vze = t->Z(0, 1);
  sp.mc_SectorEl = t->Sector(0, 1);
  sp.mc_Pex = t->Px(0, 1);
  sp.mc_Pey = t->Py(0, 1);
  sp.mc_Pez = t->Pz(0, 1);
  sp.mc_Pe = t->Momentum(0, 1);
  sp.mc_BettaEl = t->Betta(0, 1);
  sp.mc_ThetaLabEl = t->ThetaLab(0, 1);
  sp.mc_PhiLabEl = t->PhiLab(0, 1);
  sp.mc_TargType = t->TargTypeSM(dataKind, targetOption, 1);
  // gsim particle (22)
  sp.mc_pid = ToPDG(t->Id(row, 1));  // from GEANT to PDG
  sp.mc_ThetaPQ = t->ThetaPQ(row, 1);
  sp.mc_PhiPQ = t->PhiPQ(row, 1);
  sp.mc_Pt2 = t->Pt2(row, 1);
  sp.mc_Pl2 = t->Pl2(row, 1);
  Double_t fMass = particleMass(sp.mc_pid);
  Double_t fE = t->Zh(row, 1, fMass) * t->Nu(1);
  sp.mc_Zh = t->Zh(row, 1, fMass);
  sp.mc_Eh = fE;
  sp.mc_Mx2 = t->Mx2(row, 1, fMass);
  sp.mc_T = t->T(row, 1, fMass);
  sp.mc_ThetaLab = t->ThetaLab(row, 1);
  sp.mc_PhiLab = t->PhiLab(row, 1);
  sp.mc_vxh = t->X(row, 1);
  sp.mc_vyh = t->Y(row, 1);
  sp.mc_vzh = t->Z(row, 1);
  sp.mc_Sector = t->Sector(row, 1);
  sp.mc_Px = t->Px(row, 1);
  sp.mc_Py = t->Py(row, 1);
  sp.mc_Pz = t->Pz(row, 1);
  sp.mc_P = t->Momentum(row, 1);
  sp.mc_Betta = t->Betta(row, 1);
  sp.mc_Mass2 = t->Mass2(row, 1);
  sp.mc_deltaZ = t->Z(row, 1) - t->Z(0, 1);
}

#endif
